// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using betController.Contest;

namespace betController.Migrations
{
    [DbContext(typeof(contexto))]
    [Migration("20200223110957_primeraMigracion")]
    partial class primeraMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("betController.Models.Bet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("active");

                    b.Property<double>("bet_money");

                    b.Property<DateTime>("creation_date");

                    b.Property<string>("emision");

                    b.Property<int>("estado");

                    b.Property<string>("event_date");

                    b.Property<string>("evento");

                    b.Property<string>("hour");

                    b.Property<string>("player_one");

                    b.Property<string>("player_two");

                    b.Property<string>("resultado");

                    b.Property<string>("sport");

                    b.HasKey("id");

                    b.ToTable("bet_bet");
                });
#pragma warning restore 612, 618
        }
    }
}
